# Generated by Django 2.0.5 on 2018-05-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_remove_movie_duration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration_time',
            field=models.DurationField(null=True),
        ),
    ]
